<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format progress features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "#{rerun_opts} --format rerun --out rerun.txt --strict --tags ~@wip"
%>
default: --drb -r features/support/env.rb -r features/support/paths.rb -r features/step_definitions <%= std_opts %>
wip: --drb --tags @wip:3 --wip features
selenium: -r features/support/selenium.rb -r features/support/paths.rb -r features/step_definitions <%= std_opts %>
